name: Android CI
on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Root
      uses: actions/checkout@v2

    - name: Checkout Submodules
      shell: bash
      run: |
       git config --global url."https://github.com/".insteadOf "git@github.com:"
       auth_header="$(git config --local --get http.https://github.com/.extraheader)"
       git submodule sync --recursive
       git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
  
    - name: Cache Gradle and Wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Gradlew Build
      run: ./gradlew build